version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest

    commands:
      # install npm
      - echo Installing dependencies...
      - npm install --legacy-peer-deps

  build:
    commands:
      # run build script
      - echo Generating Build...
      - npm run build

artifacts:
  # include all files required to run the application
  files:
    - build/**/*
    - appspec.yml
    - scripts/**/*
