const commentsList = [
  {
    id: 1,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "05/07/2024",
  },
  {
    id: 2,

    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "05/07/2024",
  },
  {
    id: 3,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "05/07/2024",
  },
  {
    id: 4,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "05/07/2024",
  },
  {
    id: 5,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "05/07/2024",
  },
  {
    id: 6,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "05/07/2024",
  },
  {
    id: 7,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "05/07/2024",
  },
  {
    id: 8,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "05/07/2024",
  },
  {
    id: 9,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "05/07/2024",
  },
  {
    id: 10,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "05/07/2024",
  },
  {
    id: 11,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "05/07/2024",
  },
];

const feedbackList = [
  {
    id: 1,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "12 Mar, 2024",
    rating: 5,
  },
  {
    id: 2,

    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "12 Mar, 2024",
    rating: 5,
  },
  {
    id: 3,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "12 Mar, 2024",
    rating: 4,
  },
  {
    id: 4,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "12 Mar, 2024",
    rating: 3,
  },
  {
    id: 5,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "12 Mar, 2024",
    rating: 2,
  },
  {
    id: 6,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "12 Mar, 2024",
    rating: 1,
  },
  {
    id: 7,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "12 Mar, 2024",
    rating: 5,
  },
  {
    id: 8,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "12 Mar, 2024",
    rating: 4,
  },
  {
    id: 9,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "12 Mar, 2024",
    rating: 3,
  },
  {
    id: 10,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "12 Mar, 2024",
    rating: 2,
  },
  {
    id: 11,
    name: "John Doe",
    img: require("../../../assets/icons/commentPerson.png"),
    comment: "This is a great product, I love it!",
    date: "12 Mar, 2024",
    rating: 1,
  },
];

export { commentsList, feedbackList };
